FROM n8nio/runners:stable@sha256:2417957e7a347ede81424d6580f8672c0b5923609993325f61b57ab3d9d06481
USER root
RUN apk add --no-cache python3 py3-pip build-base libffi-dev || apt-get update && apt-get install -y python3 python3-pip python3-venv build-essential libffi-dev
